### ISSUE TITLE
[Question] Training reproducibility 

### ISSUE THREAD

**Issue by a240160572** [DLR-RM/stable-baselines3#973]
**Important Note: We do not do technical support, nor consulting** and don't answer personal questions per email.
Please post your question on the [RL Discord](https://discord.com/invite/xhfNqQv), [Reddit](https://www.reddit.com/r/reinforcementlearning/) or [Stack Overflow](https://stackoverflow.com/) in that case.

### Question
Hey, I am working on an algorithm comparison for my custom environment. The environment generates a random scenario for every rollout.
Therefore, training the algorithms based on the same data is preferred. 

I have tested with `set_random_seed(seed = 1)` or `env.seed(seed = 1)` for the environment.
And `model = A2C("MlpPolicy", env, seed = 1)` for the model.

None of them yields two identical training results. 

It is appreciated if you can show me how to set it properly.

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by araffin** [comment]
Hello,

> None of them yields two identical training results.

This probably means that your env does not implement the `seed()` method correctly, we have tests that actually check that for built-in gym env: https://github.com/DLR-RM/stable-baselines3/blob/master/tests/test_deterministic.py

**Comment by qgallouedec** [comment]
Sb3 works with gym 0.21 (for now). The reset method in gym 0.21 doesn't take any argument.

In gym 0.22 and above, reset takes several args including the seed. You are probably referring to the doc of gym 0.24. Aren't you?

**Comment by araffin** [comment]
> Ok, that makes sense then. I am referring to the code from https://github.com/openai/gym/blob/master/gym/envs/classic_control/cartpole.py, which is with gym 0.24.

If you want to use that version, we have instructions in the documentation to install the associated PR (#780 ).

but for now, I would recommend implementing the `seed()` method first (we have backward compat so your code won't break later when we merge the PR).

Closing as the issue comes from custom gym env and not SB3.

**Comment by a240160572** [comment]
> Closing as the issue comes from custom gym env and not SB3.

Sorry for that. 

> but for now, I would recommend implementing the `seed()` method first (we have backward compat so your code won't break later when we merge the PR).

May I ask for a hint about how to realize it with seed() in gym 0.21? Appreciate it.

**Comment by qgallouedec** [comment]
I advise you to take inspiration from the implementation of the numerous environments integrated with gym 0.21:
https://github.com/openai/gym/tree/c755d5c35a25ab118746e2ba885894ff66fb8c43

**Comment by ReHoss** [comment]
I encountered the same issue, indeed env.seed() does nothing under the gym==0.21. Could be nice to write something about this in the documentation:) ?
