### ISSUE TITLE
[Bug] `sync_envs_normalization` fails if `VecNormalize` is initialized with `norm_obs=False`

### ISSUE THREAD

**Issue by NeoExtended** [DLR-RM/stable-baselines3#912]
### 🐛 Bug

I just noticed that when an environment wrapped with a `VecNormalize` wrapper is used in combination with the `EvalCallback`, that the code exits with an `AttributeError` after calling `sync_envs_normalization`, because it cannot find the attribute `obs_rms` in the VecEnvWrapper stack.

This bug was introduced during the last version in  #768. The pull request included the optimization to not initialize `obs_rms` if it was not needed. 

I am not sure if the optimization should be reverted. An alternative would be to include a simple check to `sync_envs_normalization` if `norm_obs` is `True` or `False`.

### To Reproduce

Steps to reproduce the behavior.

```python
from stable_baselines3.common.vec_env import VecNormalize, DummyVecEnv, sync_envs_normalization
from stable_baselines3.common.env_util import make_vec_env

env = make_vec_env("CartPole-v1", vec_env_cls=DummyVecEnv, n_envs=4)
env = VecNormalize(env, norm_obs=False)

test_env = make_vec_env("CartPole-v1", vec_env_cls=DummyVecEnv, n_envs=4)
test_env = VecNormalize(env, norm_obs=False)

sync_envs_normalization(env, test_env)

```

```bash
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [5], in <cell line: 1>()
----> 1 sync_envs_normalization(env, test_env)

File ~\Anaconda3\envs\sb3\lib\site-packages\stable_baselines3\common\vec_env\__init__.py:69, in sync_envs_normalization(env, eval_env)
     67 while isinstance(env_tmp, VecEnvWrapper):
     68     if isinstance(env_tmp, VecNormalize):
---> 69         eval_env_tmp.obs_rms = deepcopy(env_tmp.obs_rms)
     70         eval_env_tmp.ret_rms = deepcopy(env_tmp.ret_rms)
     71     env_tmp = env_tmp.venv

File ~\Anaconda3\envs\sb3\lib\site-packages\stable_baselines3\common\vec_env\base_vec_env.py:312, in VecEnvWrapper.__getattr__(self, name)
    306     error_str = (
    307         f"Error: Recursive attribute lookup for {name} from {own_class} is "
    308         "ambiguous and hides attribute from {blocked_class}"
    309     )
    310     raise AttributeError(error_str)
--> 312 return self.getattr_recursive(name)

File ~\Anaconda3\envs\sb3\lib\site-packages\stable_baselines3\common\vec_env\base_vec_env.py:337, in VecEnvWrapper.getattr_recursive(self, name)
    335     attr = self.venv.getattr_recursive(name)
    336 else:  # attribute not present, child is an unwrapped VecEnv
--> 337     attr = getattr(self.venv, name)
    339 return attr

AttributeError: 'DummyVecEnv' object has no attribute 'obs_rms'

```

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)
- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by araffin** [comment]
Hello,
that was actually fixed recently in https://github.com/DLR-RM/stable-baselines3/pull/907 ;)
You have to use master version to have it though.

**Comment by NeoExtended** [comment]
Oh, i did miss that one, sorry. 
Anyway, thank you for fixing it - for now i can work with 1.4.0 until it the next version arrives :D.
