### ISSUE TITLE
Change env parameter in DummyVecEnv context

### ISSUE THREAD

**Issue by fede72bari** [DLR-RM/stable-baselines3#1488]
### ❓ Question

I need to change the parameter env._max_episode_steps for instance for CartPole in a vectorized implementation.  Without vectorization, I was using the following correctly working code 

```
env = gym.make("CartPole-v1")
env._max_episode_steps = 500000
```

passing to a vectorized environment for instance using the helper make_vec_env 

`env = make_vec_env("CartPole-v1", n_envs=8, seed=0, vec_env_cls=DummyVecEnv)`

is there a different way of defining the vectorized env allowing to change the _max_episode_steps  parameter of each env instance?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
Yes, `make_vec_env` can take a callable as input. Something like 

```python

def custom_cartpole():
    env = gym.make("CartPole-v1")
    env._max_ep_steps = 500
    return env

make_vec_env(custom_cartpole)

```

**Comment by araffin** [comment]
`make_vec_env` has a `env_kwargs` parameter too, you should be doing `gym.make("CartPole-v1", max_episode_steps=500)` in the first place (`env_kwargs = dict(max_episode_steps=500)` with the vec env).

**Comment by fede72bari** [comment]
Thank you very much guys; in all these 4 attempts

- env = gym.make("CartPole-v1", _max_episode_steps=500)
- env = gym.make("CartPole-v1", max_episode_steps=500)
- env = make_vec_env(custom_cartpole, n_envs=8, seed=0, vec_env_cls=DummyVecEnv, env_kwargs = dict(max_episode_steps=500))
- env = make_vec_env(custom_cartpole, n_envs=8, seed=0, vec_env_cls=DummyVecEnv, env_kwargs = dict(_max_episode_steps=500))

I get this error

`TypeError: __init__() got an unexpected keyword argument '_max_episode_steps'`

probably I'm editing something wrong or there is a mismatch in the Gym library version. 

Instead the idea of calling a function that instantiates a new environment with the desired max steps parameter work properly.

**Comment by araffin** [comment]
I tested it with SB3 master version (2.x) and gym 0.26/gymnasium 0.28.1.

**Comment by fede72bari** [comment]
I was running on Gym version 0.21.0 coming by default with sb3 installation. Uninstalled and installed the last version, 0.26.2. I get the same error:

env = gym.make("CartPole-v1", max_episode_steps=500)

run on Kaggle notebook, returns

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_56/2665972586.py in <module>
----> 1 env = gym.make("CartPole-v1", max_episode_steps=500)

/opt/conda/lib/python3.7/site-packages/gym/envs/registration.py in make(id, **kwargs)
    233 
    234     if default_spec:
--> 235         message += f" It provides the default version {default_spec[0].id}`."
    236         if len(env_specs) == 1:
    237             raise error.DeprecatedEnv(message)

/opt/conda/lib/python3.7/site-packages/gym/envs/registration.py in make(self, path, **kwargs)
    127     * autoreset: If to automatically reset the environment on episode end
    128     * disable_env_checker: If to disable the environment checker wrapper in `gym.make`, by default False (runs the environment checker)
--> 129     * kwargs: Additional keyword arguments passed to the environments through `gym.make`
    130     """
    131 

/opt/conda/lib/python3.7/site-packages/gym/envs/registration.py in make(self, **kwargs)
     88             f"(Currently all IDs must be of the form [namespace/](env-name)-v(version). (namespace is optional))"
     89         )
---> 90     namespace, name, version = match.group("namespace", "name", "version")
     91     if version is not None:
     92         version = int(version)

TypeError: __init__() got an unexpected keyword argument 'max_episode_steps'
```

**Comment by araffin** [comment]
> Uninstalled and installed the last version, 0.26.2. I get the same error:

Please double check that you have the correct version doing `gym.__version__`.
If you want to be sure to have a working version, you can do `pip install stable-baselines3==2.0.0a5 --upgrade` and use `import gymnasium as gym`.

```python
import gymnasium as gym # also work with import gym for gym >= 0.26.2

import stable_baselines3 as sb3
from stable_baselines3.common.env_util import make_vec_env

print(gym.__version__)
sb3.get_system_info()

assert make_vec_env("CartPole-v1")).envs[0].env._max_episode_steps == 500

vec_env = make_vec_env("CartPole-v1", env_kwargs=dict(max_episode_steps=200))

assert vec_env.envs[0].env._max_episode_steps == 200
```

It is in gym here: https://github.com/openai/gym/blob/master/gym/envs/registration.py#L504 (since https://github.com/openai/gym/pull/2748)

**Comment by fede72bari** [comment]
Good afternoon araffin, I repeated everything as you suggested. In a Kaggle notebook:

```
!pip install "stable-baselines3"
import gym as gym
gym.__version__
```

I get

`0.21.0`

Similarly, 

`sb3.get_system_info()`


returns

```
- OS: Linux-5.15.90+-x86_64-with-debian-bullseye-sid # 1 SMP Thu Apr 27 10:55:14 UTC 2023
- Python: 3.7.12
- Stable-Baselines3: 1.8.0
- PyTorch: 1.13.0+cpu
- GPU Enabled: False
- Numpy: 1.21.6
- Gym: 0.21.0
```

The testing code

```
assert make_vec_env("CartPole-v1").envs[0].env._max_episode_steps == 500
vec_env = make_vec_env("CartPole-v1", env_kwargs=dict(max_episode_steps=200))
assert vec_env.envs[0].env._max_episode_steps == 200
```
Give the previous error:

```
[...]
TypeError: __init__() got an unexpected keyword argument 'max_episode_steps'
```

At this point, I uninstall Gym and re-install a newer version

```
!pip uninstall Gym -y
!pip install Gym > 0.21
```

now I noted this interesting thing:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
**stable-baselines3 1.8.0 requires gym==0.21, but you have gym 0.26.2 which is incompatible.**
```

So I upgrade stable baseline3 (why was not taken the last version?), stop and re lunched the kernel, then

`pip install stable-baselines3==2.0.0a5 --upgrade` 

```
gym.__version__
''0.23.1''
```

and 

```
import stable_baselines3 as sb3
sb3.get_system_info()
```

gives

```
- OS: Linux-5.15.90+-x86_64-with-debian-bullseye-sid # 1 SMP Thu Apr 27 10:55:14 UTC 2023
- Python: 3.7.12
- Stable-Baselines3: 2.0.0a5
- PyTorch: 1.13.0+cpu
- GPU Enabled: False
- Numpy: 1.21.6
- Cloudpickle: 2.2.1
- Gymnasium: 0.28.1
- OpenAI Gym: 0.26.2
```

Now it works. I think the problem was not on the Gym version since I had upgraded it, but in the SB3 version that was not the last one. Thank you all.
