### ISSUE TITLE
SimpleMultiObsEnv()

### ISSUE THREAD

**Issue by ziegenbalg** [DLR-RM/stable-baselines3#453]
**Important Note: We do not do technical support, nor consulting** and don't answer personal questions per email.
Please post your question on the [RL Discord](https://discord.com/invite/xhfNqQv), [Reddit](https://www.reddit.com/r/reinforcementlearning/) or [Stack Overflow](https://stackoverflow.com/) in that case.

### 📚 Documentation

I've tried implementing the example given in docs/guide/examples.rst for the Dict Obs Env ([link](https://github.com/DLR-RM/stable-baselines3/blob/master/docs/guide/examples.rst#dict-observations)). It feels like the underlying DictWrapper expects the Obs Dict to be in a specific format that may not be very well documented. 
I have read both: 
https://github.com/DLR-RM/stable-baselines3/blob/master/docs/guide/examples.rst
https://github.com/DLR-RM/stable-baselines3/blob/master/docs/guide/custom_env.rst
and I swear there was a third that outlined the correct structure Dict/Vec Env's need to have but I cant find it now...

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

Long story short I keep getting a key error from the VecEnvWrapper as it's expecting the Obs Dict to have a 'observation' and later an 'action' key. Did something change in the code and not the documentation yet? I've attached an example program.

> Using cuda device
Traceback (most recent call last):
  File "/home/eziegenbalg/Documents/ppo.py", line 237, in <module>
    run_experiment()
  File "/home/eziegenbalg/Documents/ppo.py", line 203, in run_experiment
    agent = PPO(
  File "/usr/local/lib/python3.9/site-packages/stable_baselines3/ppo/ppo.py", line 95, in __init__
    super(PPO, self).__init__(
  File "/usr/local/lib/python3.9/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 76, in __init__
    super(OnPolicyAlgorithm, self).__init__(
  File "/usr/local/lib/python3.9/site-packages/stable_baselines3/common/base_class.py", line 156, in __init__
    env = self._wrap_env(env, self.verbose, monitor_wrapper)
  File "/usr/local/lib/python3.9/site-packages/stable_baselines3/common/base_class.py", line 209, in _wrap_env
    env = ObsDictWrapper(env)
  File "/usr/local/lib/python3.9/site-packages/stable_baselines3/common/vec_env/obs_dict_wrapper.py", line 28, in __init__
    self.obs_dim = venv.observation_space.spaces["observation"].shape[0]
KeyError: 'observation'

Simple PPO:
[ppo.zip](https://github.com/DLR-RM/stable-baselines3/files/6540560/ppo.zip)

Update 1:
The above key error only seems to affect the pip repo v1.0 of stable-baselines after upgrading to 1.1.0a9 it has progressed to a 'flatten' layer not being avaiable:

> Using cuda device
Wrapping the env in a VecTransposeImage.
Traceback (most recent call last):
  File "/home/eziegenbalg/Documents/ppo.py", line 237, in <module>
    run_experiment()
  File "/home/eziegenbalg/Documents/ppo.py", line 211, in run_experiment
    agent.learn(total_timesteps=1000)
  File "/home/eziegenbalg/Documents/goldengoose-research/stable-baselines3/stable_baselines3/ppo/ppo.py", line 300, in learn
    return super(PPO, self).learn(
  File "/home/eziegenbalg/Documents/goldengoose-research/stable-baselines3/stable_baselines3/common/on_policy_algorithm.py", line 235, in learn
    continue_training = self.collect_rollouts(self.env, callback, self.rollout_buffer, n_rollout_steps=self.n_steps)
  File "/home/eziegenbalg/Documents/goldengoose-research/stable-baselines3/stable_baselines3/common/on_policy_algorithm.py", line 167, in collect_rollouts
    actions, values, log_probs = self.policy.forward(obs_tensor)
  File "/home/eziegenbalg/Documents/goldengoose-research/stable-baselines3/stable_baselines3/common/policies.py", line 563, in forward
    latent_pi, latent_vf, latent_sde = self._get_latent(obs)
  File "/home/eziegenbalg/Documents/goldengoose-research/stable-baselines3/stable_baselines3/common/policies.py", line 581, in _get_latent
    features = self.extract_features(obs)
  File "/home/eziegenbalg/Documents/goldengoose-research/stable-baselines3/stable_baselines3/common/policies.py", line 128, in extract_features
    return self.features_extractor(preprocessed_obs)
  File "/usr/local/lib64/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/eziegenbalg/Documents/goldengoose-research/stable-baselines3/stable_baselines3/common/torch_layers.py", line 48, in forward
    return self.flatten(observations)
  File "/usr/local/lib64/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib64/python3.9/site-packages/torch/nn/modules/flatten.py", line 40, in forward
    return input.flatten(self.start_dim, self.end_dim)
AttributeError: 'dict' object has no attribute 'flatten'

**Comment by araffin** [comment]
Hello,
Please fill in the issue template correctly.
It seems that you are not using the latest stable-baselines3 version (please install the master version, cf docs for how to do that).

**Comment by ziegenbalg** [comment]
I updated the original post following the template, sorry about that. You were right, after updating from v1.0 that was installed via pip to the development branch 'master' it is now able to find the 'observation' key. However we now get a flatten layer not found error. Investigating further.

**Comment by araffin** [comment]
again please use the custom env issue template and the env checker.

**Comment by araffin** [comment]
You are probably using a `MlpPolicy` instead of a `MultiInputPolicy` (cf doc)

**Comment by ziegenbalg** [comment]
@araffin thank you for your help. Changing it back to MultiInputPolicy fixed the issue! I was using MultiInputPolicy at first, but that didn't exist in stable-baselines3 v1.0.
Lesson learned, always try the dev branch first.

**Comment by araffin** [comment]
> Lesson learned, always try the dev branch first.

well, the documentation corresponds to the master version.
If you want a specific SB3 version, you can select it at the bottom left.
